# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class CandidateStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    INTERVIEWING = 'INTERVIEWING'
    OFFERED = 'OFFERED'
    HIRED = 'HIRED'
    REJECTED = 'REJECTED'

class CandidateCareerLevel(StrEnum):
    ENTRY_LEVEL = 'ENTRY_LEVEL'
    MID_LEVEL = 'MID_LEVEL'
    SENIOR_LEVEL = 'SENIOR_LEVEL'
    DIRECTOR_LEVEL = 'DIRECTOR_LEVEL'
    C_LEVEL = 'C_LEVEL'

class CandidateInterest(StrEnum):
    UNKNOWN = 'UNKNOWN'
    NOT_INTERESTED = 'NOT_INTERESTED'
    OPEN_TO_WORK = 'OPEN_TO_WORK'

class CompanyStage(StrEnum):
    PRE_SEED = 'PRE_SEED'
    SEED = 'SEED'
    SERIES_A = 'SERIES_A'
    SERIES_B = 'SERIES_B'
    SERIES_C = 'SERIES_C'
    SERIES_D = 'SERIES_D'
    PUBLIC = 'PUBLIC'
    PRIVATE = 'PRIVATE'

class JobStatus(StrEnum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'
    ON_HOLD = 'ON_HOLD'
    FILLED = 'FILLED'

class CompanySize(StrEnum):
    SIZE_1_10 = 'SIZE_1_10'
    SIZE_10_50 = 'SIZE_10_50'
    SIZE_50_100 = 'SIZE_50_100'
    SIZE_100_250 = 'SIZE_100_250'
    SIZE_250_500 = 'SIZE_250_500'
    SIZE_500_1000 = 'SIZE_500_1000'
    SIZE_1000_5000 = 'SIZE_1000_5000'
    SIZE_5000_PLUS = 'SIZE_5000_PLUS'

class Industry(StrEnum):
    TECHNOLOGY = 'TECHNOLOGY'
    FINANCE = 'FINANCE'
    HEALTHCARE = 'HEALTHCARE'
    EDUCATION = 'EDUCATION'
    MANUFACTURING = 'MANUFACTURING'
    RETAIL = 'RETAIL'
    ENERGY = 'ENERGY'
    TRANSPORTATION = 'TRANSPORTATION'
    ENTERTAINMENT = 'ENTERTAINMENT'
    HOSPITALITY = 'HOSPITALITY'
    GOVERNMENT = 'GOVERNMENT'
    NON_PROFIT = 'NON_PROFIT'
    REAL_ESTATE = 'REAL_ESTATE'
    CONSULTING = 'CONSULTING'
    TELECOMMUNICATIONS = 'TELECOMMUNICATIONS'
    AGRICULTURE = 'AGRICULTURE'
    OTHER = 'OTHER'

