packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - prisma
dedupeDirectDeps: true
packageImportMethod: "auto"
includeWorkspaceRoot: true
resolvePeersFromWorkspaceRoot: true
injectWorkspacePackages: true
